spring.application.name=seniorProject

k

spring.datasource.url = jdbc:postgresql://localhost:5432/SeniorProject



spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
