spring.application.name=seniorProject

spring.datasource.url = jdbc:postgresql://monorail.proxy.rlwy.net:58345/railway
spring.datasource.username = postgres
spring.datasource.password = xGOporJUmNguMzKQLLkorCrZZbsEbtBA


spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

