spring.application.name=seniorProject

key=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

spring.datasource.url = jdbc:postgresql://localhost:5432/SeniorProject
spring.datasource.username = postgres
spring.datasource.password = 12345


spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
